name: Deploy AtoM to Azure VM

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Azure VM via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 20.151.163.248       # your VM IP
          username: assia            # your VM user
          key: ${{ secrets.AtomGithubaction }}
          script: |
            cd /usr/share/nginx/atom
            git pull origin main
            php symfony cc
            sudo systemctl restart php8.1-fpm
            sudo systemctl restart nginx
