name: Deploy to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 20.151.163.248 >> ~/.ssh/known_hosts

      - name: Update code on VM
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          ssh assia@20.151.163.248 "
            cd /usr/share/nginx/atom && \
            git fetch https://$GH_TOKEN@github.com/AssiaAouina06/atom-project.git main && \
            git reset --hard FETCH_HEAD
          "
