name: Deploy to Azure VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy code to VM
      run: |
        ssh -o StrictHostKeyChecking=no assia@<YOUR_VM_IP> "
          cd /usr/share/nginx/atom &&
          git fetch origin main &&
          git reset --hard origin/main
        "
      env:
        AZ_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
